import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Next.js 14 Login Register MongoDB Next-Auth Login Authentication Daisyui Tailwind",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-gray-300 h-screen`}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
